language: python
sudo: false
python: 3.5
cache:
  pip: true
git:
  depth: false
branches:
  except:
  - gh-pages
before_install:
- pip install --upgrade pip setuptools wheel
install:
- pip install memote
script:
- git checkout "${TRAVIS_BRANCH}"
- ./scripts/travis_deploy.sh
env:
  global:
    secure: d3DebGRNkzl6l8kUN+dtV/MBPQtlf4HhyD/MQuQ43vvexDOun0Id1NldFZ36mlNL5O1dTf10rrRiy/ITmAHRveL45wSshqByZ9vsv3wqpSK8H520hLUSBTpaJc/cqPuznGnPH/urOK7GrFvaICkRFPPgkE7r4lXuLxVNO0yR0ldxt3oRXGAL4mFuY1PXqNI1AbIbv1Z1NFoY3tRU8k2OGFhcob9ShH+mhm2GzK/vPuLTA5Q8oxJIg6nfvamsC5CueDuunJem1r9os1qtNqb7G0C9abaPuKCeX1DaRKm5Y7NYwdMEy+vAs7mQ50F/3NFU6B84Jrnf3j6ISo1wbJ1YLex/nlO3toErAifmoIQIUm9Es12VUmYTNnUdjxNsnX8AhXdSGWecEJIiPWl7F1eX6nnehQv517Dy4Vv3ZPAgGZ6pZ2MCxe2Zr8nArJGg3C3geKAPgaUikQ+UP+t7Ao/0Zdo+YT2qiU3rdwaUD5JmFAwpJq+Vwjh3n1RQCBQD4U0JDR6of5v6TxLI7Ek5hQ9WEMozNTCDyOy8ci2w78kyWul7YN3sDaWGUJedUGWp8LtM8MUK55c9ZVI7L7sAcFAvZYeqr+2X3283ZrUWfjrxUf8WoIWwNGEqbjVkZLWTy9JmKp1iK9GCYvyMNdDpX1G/FXARPXlr9O/QifsQO4gR7f0=
